<?php
/**
 * Auther: Joshua Conero
 * Date: 2017/6/15 0015 23:28
 * Email: brximl@163.com
 * Name:
 */

namespace app\common\model;


use think\Config;
use think\Model;

class Fnc0020c extends Model
{
    protected $pk = 'listid';
    protected $table = 'fnc0020c';
    // 初始化
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $uid = getUserInfo('uid');
        // 自动写入：现金 (未初始化时)
        if(Config::get('setting.fnc_master_init') == 'Y' && $uid){
            $count = $this->db()
                ->where('uid',$uid)
                ->count();
            if(empty($count)){
                $this->db()
                    ->insert([
                        'name'  => '现金',
                        'type'  => 'M0',
                        'uid'   => $uid,
                        'remark'=> '[系统]于'.date('Y-m-d H:i:s').'初始化时自动生成'
                    ]);
            }
        }
    }
}